### PR TITLE
Use protocol relative URI to load JavaScripts

### PR DESCRIPTION
**Pull request by tisba**
Modern browsers won't load insecure content when the origin page was loaded over TLS. I noticed that https://blacklabel.github.io/custom_events/ doesn't work for me (Chrome 43.0.2357.130).

### CODE REVIEW

**Comment by tisba** [comment]
-bump-

**Comment by sebastianbochan** [comment]
Hi @tisba,
I lost the notification about it. Thank you for PR and I merged it.

**Comment by tisba** [comment]
:)

Don't forget to update https://blacklabel.github.io/custom_events/ as this still won't working currently in all modern browsers.

**Comment by sebastianbochan** [comment]
Right, I did it in the commit here: 

https://github.com/blacklabel/custom_events/commit/62cad5d1d9a3cffd81939bb5beaff8dab0f14a65

**Pull request merged**
